server:
  port: 8081

spring:
    datasource:
        name: test
        url: jdbc:mysql://47.94.57.213:3306/citymanagement?zeroDateTimeBehavior=convertToNull
        username: admin
        password: 123.com
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: main.java.com.entity  # 注意：对应实体类的路径
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    page-size-zero: true
token:
  AK: eykihlb123
  SK: POS123
ftpServer:
  ftpHost: 47.94.57.213
  ftpUserName: ftpuser
  ftpPassword: Aa1905.
  ftpPort: 21
  ftpPath: "/home/ftplocal"
  localPath: F:/download
  httpHost: 47.94.57.213
  httpPort: 80
  httpPath: ""
